server:
  port: 9099
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new_store?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root # 数据库用户名
    password: 123456 # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver # 驱动类
  jpa:
    hibernate:
      ddl-auto: update # 自动更新表结构（可选：none/update/create-drop）
    show-sql: true # 打印SQL日志
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 6
    # 密码
    password: wz123456
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

mybatis:
  mapper-locations: classpath:mapper/*.xml # XML映射文件路径
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名转换
logging:
  level:
    root: info # 全局日志级别
    org.springframework.web: debug # Spring Web日志（调试时开启）
    com.your.package: debug # 自定义包日志

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true

# JWT配置
jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加解密使用的密钥
  secret: t7XmZQ9FpJ2vR4cK6yLbW8nSdE3gA5hC1fUoMqP0iYjVrNlOxBwGzTkHvIeD
  # JWT的超期限时间（60*60*24）
  expiration: 86400
  # JWT负载中拿到开头
  tokenPrefix: Bearer
