server:
  port: 9099

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new_store?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 自动更新表结构（可选：none/update/create-drop）
    show-sql: true # 打印SQL日志
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379
    database: 9
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    password: wz123456
  # RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 消息确认配置
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    # 消费者配置
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 10
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wyc.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 断路器配置
resilience4j:
  circuitbreaker:
    instances:
      searchService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      getHotProducts:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      getNewProducts:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  ratelimiter:
    instances:
      getHotProductsRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 3s
      getNewProductsRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 3s
  bulkhead:
    instances:
      getHotProductsBulkhead:
        maxConcurrentCalls: 20
        maxWaitDuration: 500ms
      getNewProductsBulkhead:
        maxConcurrentCalls: 20
        maxWaitDuration: 500ms

# 日志配置
logging:
  level:
    com.wyc: debug
    org.springframework: warn

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true

# JWT配置
jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加解密使用的密钥
  secret: t7XmZQ9FpJ2vR4cK6yLbW8nSdE3gA5hC1fUoMqP0iYjVrNlOxBwGzTkHvIeD
  # JWT的超期限时间（60*60*24）
  expiration: 86400
  # JWT负载中拿到开头
  tokenPrefix: Bearer

# 线程池配置
thread-pool:
  core-pool-size: 10
  max-pool-size: 20
  queue-capacity: 100
  keep-alive-seconds: 60
  thread-name-prefix: wyc-async-
